### ISSUE TITLE
SSL Certificate Validation Callback

### ISSUE THREAD

**Issue by senj** [NullDesk/NullMailer#52]
Hi,

in MailKit it is possible to provide a method to make the SSL certificate validation in code.
Is it possible to add this to NullMailer or is there a way to do that already?

I wonder why I need the Certificate at all as I connect via SMTP port 25.

Thanks

**Comment by StephenRedd** [comment]
I'm sure it is possible. MailKit/MimeKit seems to have support for certificate based authentication mechanisms built in, though I'm personally not familiar with mail services that require client certificates. 

Mostly, I think all I'd need to do is provide support for defining certificate details in settings, and passing that info along to the MailKit services if they're provided in the settings (like it does with username and password settings now). 

Thing is, I don't know how to test it, since I don't happen to have a lot of locally installed mail servers just kicking around. 

If I made a beta package that had support for this, would be be able to do the code review and test if it works? Or could you point me to a quick way to setup a mail service locally that would let me test certificate scenarios (on windows)?

**Comment by senj** [comment]
Hi Stephen, thanks for your reply and sorry for the delay.
We had another admin here and fixed the certificate problem.

The method I was referring to was [this](http://www.mimekit.net/docs/html/P_MailKit_MailService_ServerCertificateValidationCallback.htm)

What's missing for me now it that flag to tell the client which SSL we use. Currently only the true / false override is supported, but having [this](http://www.mimekit.net/docs/html/M_MailKit_Net_Smtp_SmtpClient_Connect_1.htm) with [that](http://www.mimekit.net/docs/html/T_MailKit_Security_SecureSocketOptions.htm) would be great.

**Comment by StephenRedd** [comment]
Thanks for the update. I'll make time in the next few days, or over the weekend, to work on this.

**Comment by StephenRedd** [comment]
I've look into this in more detail. It seems what you were doing is validating (or overriding the default validation) for the SMTP server's certificate; not using client certificates as I'd initially thought. 

Based on the documentation, the best way to accomplish this with the current framework would be for the consuming application to supply it's own instance of the MailKit SMTP client and pass it in via the MkSmtpMailer's overloaded constructor .

```
var client = new SmtpClient
{
    // setup a validation callback, this one basically just overrides the default check
    //    Useful if the default validation would fail; e.g. server uses an untrusted cert
    ServerCertificateValidationCallback = (s, c, h, e) => true
};
var mkOptions = new OptionsWrapper<MkSmtpMailerSettings>(new MkSmtpMailerSettings
{
    //setup options here
});
var m = new MkSmtpMailer(client, mkOptions);
```

The SecureSocketOptions is a bit more complex. The way it is setup now, the mailer's setting only chooses if SSL is required, or if it is optional. Yes, the connection will use try to use SSL if the server supports it. 

I'm going to do a bit more research before I decide what changes to make related to SMTP authentication. Maybe just changing that option's name would clarify the effect it has when set.

There is still some need for more complex SMTP configuration settings though; for example using GMail would be difficult with the current configuration, and it would be nice to support client certificates and access tokens too.

**Comment by senj** [comment]
These are great information. Thank you for your investigation.
If I would have seen this remark about using SSL even when set to false earlier there would have been less confusion.

**Comment by StephenRedd** [comment]
The code changes are ready, but before calling this done I want to add integration tests specific to working with gmail authentication, and update the documentation.

**Comment by StephenRedd** [comment]
Gmail and support for token authentication in general seems to work, but in practice some effort would be needed by the consuming application to ensure the mailer instances always have a valid token (since they expire). Typically, this means these consumers will have to manage the token in the settings dynamically, rather than reading them from a static config file.
